server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "Authorization"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: auth-internal
          uri: http://auth-service:8081
          predicates:
            - Path=/internal/users/**

        - id: auth-user-service
          uri: http://auth-service:8081
          predicates:
            - Path=/user/**

        - id: task-service
          uri: http://task-service:8082
          predicates:
            - Path=/tasks/**

        - id: task-internal
          uri: http://task-service:8082
          predicates:
            - Path=/internal/tasks/**

jwt:
  secret: ${JWT_SECRET}